[hololens]
container = "ghcr.io/hologit/lenses/sencha-app:latest"

[hololens.sencha]
app = "EmergenceEditor"

[hololens.input]
root = "sencha-workspace"
files = [
    "workspace.json",
    "ext/**",
    "packages/**",
    "EmergenceEditor/**",
]

[hololens.output]
root = "webapp-builds/EmergenceEditor"
merge = "replace"
